google/vim-codefmt

autoload/codefmt.vim
vroom/autocmd.vroom
vroom/main.vroom

Fix vroom tests to not depend on executables installed on host

---

autoload/codefmt.vim
doc/codefmt.txt
instant/flags.vim

mb it make sense to generalize them somehow?
because it's almost the same as gofmt one

feat(formatters): add autopep8

---

autoload/codefmt.vim
instant/flags.vim
vroom/autocmd.vroom
vroom/autopep8.vroom
vroom/clangformat.vroom
vroom/gofmt.vroom
vroom/main.vroom

Cleans up vroom files so they explain what they're doing more clearly and introduce concepts in a more natural order. Cuts down on a lot of repetition by leaving out details that don't relate to the feature being demonstrated/tested, like using more wildcards in syscall lines and formatting empty buffers in places.
Also adds a lot of coverage and adds testing for autopep8 which previously had none.
Fixes #11.

Clean up vroom files to introduce concepts better, add autopep8 coverage

---

.travis.yml
bootstrap.vim

Update the Travis CI build to test against the minimum required version of Maktaba as well as the current HEAD version.
Fixes #35.

Test against the version of Maktaba we require.

---

.travis.yml
README.md
addon-info.json
autoload/codefmt.vim
bootstrap.vim
doc/codefmt.txt
instant/flags.vim
vroom/main.vroom

This change removes the codefmt->codefmtlib dependency, replacing it with the new extension registry added in Maktaba 1.9.0.
In detail:
- Replace codefmtlib references with `maktaba#extensions`.
- Bump the requirements to Maktaba 1.9.0.
- Inline the documentation and EnsureFormatter() method from codefmtlib.
- Inline (and slightly adjust) some of the tests from codefmtlib.
- Register jsbeautify before clang-format so that clang-format is still the default formatter for filetype javascript. (codefmtlib was first-registration wins, maktaba#extensions is last-registration wins.)
Fixes #32.

Use Maktaba's extension registry rather than codefmtlib.

---

.travis.yml
bootstrap.vim
instant/flags.vim
vroom/autocmd.vroom
vroom/autopep8.vroom
vroom/clangformat.vroom
vroom/extensions.vroom
vroom/gofmt.vroom
vroom/jsbeautify.vroom
vroom/main.vroom
vroom/setupvroom.vim

Moves testing setup code out of bootstrap.vim (because it's only supposed to get the plugin installed, not try to install glaive from custom paths, etc.). Also moves the maktaba version check so it will trigger for all users and not just any users that source bootstrap.vim.
Fixes #39.

Remove testing hacks and maktaba version check from bootstrap.vim

---

autoload/codefmt.vim
doc/codefmt.txt

Our two formatters are clang-format and gofmt... and autopep8.

Fix a trivial documentation typo.

---

autoload/codefmt.vim
plugin/autocmds.vim
plugin/commands.vim

Say you have :AutoFormatBuffer enabled and you're editing file. Then you change a line, save it, because why not. You then go to another line and hit . to replay that change, it reformats the code.
In my opinion it's pretty clear that the behavior is weird in this situation. I honestly don't see when having code formatting be something that is repeatable via . is useful but I'd be interested to hear the reasoning behind it. [#45]
This fixes it.

AutoFormatBuffer no longer sets repeat

---

.travis.yml
autoload/codefmt.vim
instant/flags.vim
vroom/autocmd.vroom
vroom/clangformat.vroom
vroom/jsbeautify.vroom
vroom/main.vroom

Adds cursor support and java support with conditional version checking for both.  I have not regenerated the documentation, because my experiments with vimdoc failed.

Add cursor support

---

autoload/codefmt.vim
vroom/clangformat.vroom

Pass -sort-includes to clang-format 3.8 and above.

---

autoload/codefmt.vim

This isn't perfect, since it doesn't try to parse the yapf output, but it at least won't overwrite the file if there's an error.

Fixes #61: Catch yapf errors instead of overwriting file

---

autoload/codefmt.vim
vroom/clangformat.vroom

`-sort-includes` was added in LLVM r248367, and is enabled-by-default as of r253202, both of which will presumably be included in LLVM 3.8 (which hasn't yet been released).
Removing this flag allows `:FormatCode` to work with development clang-format versions in the range [r242222, r248367), which identify as 3.8.0 but don't support `-sort-includes`.
This effectively reverts cb42d28. Fixes #64.

Stop passing -sort-includes to clang-format

---

vroom/jsbeautify.vroom

Prior to #96 (3dad76a and 8e54240), the js-beautify binary was invoked with the wrong --type argument.
This change verifies the js-beautify arguments for each of the supported filetypes (so that we can verify the fixes above), and also explains what's wrong with the javascript filetype support (it's picked up by clang-format instead).

Improve jsbeautify tests

---

autoload/codefmt/clangformat.vim

Enable clang-format for objc/objcpp files.

---

autoload/codefmt/buildifier.vim
vroom/buildifier.vroom

This was broken by 4b6cb67, which caused error messages to contain the filename rather than 'stdin'.
Fixes #103

Fix buildifier error reporting.

---

.travis.yml
instant/flags.vim
vroom/setupvroom.vim

Four problems that were preventing the vroom tests from running on
neovim:
- The vroom version was too old, see
https://github.com/google/vroom/pull/104
- The maktaba version was too old, see
https://github.com/google/vim-maktaba/issues/172. I considered
constraining this to neovim but it applies to recent vim as well (the
version of vim in travis/xenial is quite old) and the extra version
checking seems pointless.
- The get-pip.py invocation was outdated.
- For some reason neovim pauses more often with "Hit ENTER" messages.
Perhaps newer vim would too. In any case, increasing the cmdheight
solves the problem without needing to sprinkle :silent everywhere.

fix: neovim vroom tests

---

autoload/codefmt/autopep8.vim
autoload/codefmt/buildifier.vim
autoload/codefmt/dartfmt.vim
autoload/codefmt/formatterhelpers.vim
autoload/codefmt/gofmt.vim
autoload/codefmt/googlejava.vim
autoload/codefmt/jsbeautify.vim
autoload/codefmt/rustfmt.vim
autoload/codefmt/shfmt.vim
autoload/codefmt/zprint.vim
doc/codefmt.txt

Creates helper functions for the boilerplate of common operations in formatter implementations: `codefmt#formatterhelpers#Format({cmd})` and `codefmt#formatterhelpers#AttemptFakeRangeFormatting({startline}, {endline}, {cmd})`. These make conventions more obvious and help any intentional differences from the most common boilerplate version stand out more obviously.

Implement common helper functions for common formatting operations

---

autoload/codefmt/formatterhelpers.vim
autoload/codefmt/prettier.vim
autoload/codefmt/zprint.vim

Refactor some common boilerplate so that it's easier to apply this logic
to executables and options across all plugins. Implemented in prettier
and zprint for starters, with no functional changes to either plugin.
Extracted from https://github.com/google/vim-codefmt/pull/136

refactor: add codefmt#formatterhelpers#ResolveFlagToArray

---

autoload/codefmt/zprint.vim
vroom/zprint.vroom

This avoids the syscall failing if the directory doesn't exist yet. It's
an unlikely scenario, but I managed to hit it, and it's annoying when
tooling breaks in unlikely scenarios...

fix(zprint): don't cd unless dir exists

---

vroom/zprint.vroom

Fixes https://github.com/google/vim-codefmt/issues/140

fix(zprint): vroom no-op system hijacks

---

autoload/codefmt/prettier.vim
doc/codefmt.txt
instant/flags.vim
vroom/prettier.vroom

If npx is available, use it for running prettier. This will find a project-local prettier, if available, which allows everybody on the team to run the same version. Otherwise people have different prettier versions, and code formatting toggles back and forth between commits.
Since npx can't tell us if prettier is available, we check with `npx prettier --version` and cache the result.
Also, since by default npx will do a temporary install of things you try to run, we use the `--no-install` flag to avoid that. We only want npx to find what's already there.
Along the way, kill the opinionated prettier options that were in vim-codefmt, since they unhelpfully override local and project config files.

feat(prettier): use npx for project-local prettier

---

autoload/codefmt/prettier.vim

This changed in Prettier 2.0, and apparently was never needed. See
https://prettier.io/blog/2020/03/21/2.0.0.html#remove---stdin-7668httpsgithubcomprettierprettierpull7668-by-thorn0httpsgithubcomthorn0

fix(prettier): drop --stdin parameter

---

autoload/codefmt/clangformat.vim

Also make version check logic a little more explicit and fix quirks for empty version or comparing shorter versions.
Resolves a ShellError bug when invoking some versions of the clang-format tool that return non-zero exit code, and instead makes it so if the tool returns a parseable version number it will be used regardless of exit code.
The material change was just updating `.Call()` to `.Call(0)`, but I refactored the version check logic a little in the process to make sure the scenario of empty version number is handled properly. Also adjusts the logic for comparing versions of mismatched lengths to pad version with zeros instead of checking length only, which could false negative on long min version values.
Fixes #84 .

Ignore non-zero exit code from clang-format --version

---

README.md
autoload/codefmt/clangformat.vim

Arduino (https://www.arduino.cc/) source files (.ino filename extension) are essentially a c++ files, but recognized as a separate file type by vim (for Arduino-specific syntax highlighting, I believe). 
Arduino IDE, which uses .ino files for user source code, provides for external editor support, which could be vim.
I found it helpful to associate arduino files with clang-format, which works well for me.

associate arduino file-type with clang-format

---

autoload/codefmt/clangformat.vim
vroom/clangformat.vroom

This bug (and a related predecessor) cause `:goto` and `line2bytes()`
to do the wrong thing when vim textprops are used.
This manifests as "cursor jumps around randomly after formatting" when using
plugins that use textprops for diagnostics, highlighting etc.
We happen to have all the code in an array when we need to do cursor coordinate
conversions, so we do those in vimscript instead of querying vim.
Without this patch, The newly added test fails on affected versions of vim
including both vim master and debian's 8.1.2269 (in different ways).
Vim bug tracker entry:
https://github.com/vim/vim/issues/5930
Similar workaround in first-party vim integration:
https://github.com/llvm/llvm-project/commit/591be7ec500c151d9232366042e21c74e006292c

clang-format: work around vim/vim#5930 when positioning cursor

---

autoload/codefmt/prettier.vim

Minor fix that only impacts unnamed buffers: `babylon` was deprecated in v1.16.0 (prettier/prettier#5647) and removed in v2.0.0 (prettier/prettier#7533).

Fix default parser for Prettier (babylon -> babel)

---

autoload/codefmt/clangformat.vim
doc/codefmt.txt

Solves #123 by applying handling of `clang_format_executable` similar to the existing handling of `google_java_executable`

Add support for an arbitrary clang_format command with arguments

---

autoload/codefmt/shfmt.vim
doc/codefmt.txt
instant/flags.vim

Make it possible to use complex shfmt commands, such as shfmt running in a docker container. Use the codefmt#formatterhelpers#ResolveFlagToArray approach seen in other formatters.
Similar to https://github.com/google/vim-codefmt/pull/124

Add support for arbitrary shfmt command with arguments

---

autoload/codefmt.vim
autoload/codefmt/formatterhelpers.vim

Prints user-friendly errors if a formatter fails an IsAvailable call (also allowing other formatters to still be checked), and fixes a particular "type mismatch" error encountered on vim versions older than
7.4.1546.
Fixes #155.

IsAvailable: Fix "type mismatch" and print nicer errors

---

vroom/autocmd.vroom
vroom/buildifier.vroom
vroom/fish_indent.vroom
vroom/main.vroom
vroom/rustfmt.vroom
vroom/shfmt.vroom
vroom/zprint.vroom

Fix some subtle issues that were being ignored by the default message strictness `GUESS-ERRORS` and explicitly capture some echo messages into vroom tests so they can pass even in STRICT mode.

Adjust vroom tests to work with --message-strictness=STRICT

---

autoload/codefmt/yapf.vim

Treat any yapf exit code as an error case, not just exit code 1

---

vroom/luaformatterfiveone.vroom

Fixes vroom tests that apparently broke with #167, but somehow didn't get executed by Travis CI.
Note: Leaving the neovim mode failures to fix in a subsequent change.

Fix luaformatterfiveone.vroom failures

---

autoload/codefmt/jsbeautify.vim

The mustache/vim-mustache-handlebars plugin sets the filetype to either
html.handlebars or html.mustache. Even though js-beautify supports
formatting for these files, the `--type` parameter must be `html`.
This commit sets the `--type` parameter to `html` when the filetype
matches the regex `html\..*`.

js-beautify support for mustache and handlebars

---

vroom/autopep8.vroom
vroom/clangformat.vroom
vroom/jsbeautify.vroom

Fixes several vroom tests that wrongly assume their formatter will be the default for a given filetype and started failing when I reordered the formatter registrations in b1b51098.
Note those precedence changes could really affect users, but only if they're relying on defaults and have multiple installed formatters for those same filetypes. If so, it's easily resolved by explicitly specifying a formatter name or uninstalling unwanted formatters.

Tests: Fix several failures related to formatter precedence

---

autoload/codefmt/clangformat.vim
vroom/clangformat.vroom

- FIXME: this test doesn't actually do anything yet
- Do not call clang-format if buffer is empty.
I did my best to generate a unit test that duplicates the bug, however I've stared
it at so long I'm going cross-eyed and I still cannot figure out a good way to do this.
My problem is I'm not sure how to check the output of `:FormatCode clang-format` for
an error (or lack thereof). I tried using a `try-catch` but was unsure how to
do this with vroom while still intercepting the system calls to provide a mocked
response.
Any help on figuring out a good unit test for this would be greatly appreciated.

Don't call clang-format on empty buffer

---

autoload/codefmt/buildifier.vim
doc/codefmt.txt
instant/flags.vim

In your vimrc you can do e.g.
```
call glaive#Install()
Glaive codefmt buildifier_lint_mode='fix'
```
to get buildifier to autofix issues. The default behaviour is unchanged.

Add --lint_mode flag for buildifier

---

README.md
autoload/codefmt/swiftformat.vim
doc/codefmt.txt
instant/flags.vim
plugin/register.vim
vroom/swiftformat.vroom

This PR adds the option to autoformat swift code using Apple's [swift-format](https://github.com/apple/swift-format).
Linked issue: https://github.com/google/vim-codefmt/issues/194

Add swift autoformatting using swift-format

---

autoload/codefmt/buildifier.vim
doc/codefmt.txt
instant/flags.vim

In your vimrc you can do e.g.
```
call glaive#Install()
Glaive codefmt buildifier_lint_mode='fix'
Glaive codefmt buildifier_warnings='-module-docstring,+unsorted-dict-items'
```
to get buildifier to ignore missing module docstrings but sort
dictionaries automatically. The default behaviour is unchanged.

Add --warnings flag for buildifier

---

README.md
autoload/codefmt/ormolu.vim
instant/flags.vim
plugin/register.vim
vroom/ormolu.vroom

Add ormolu formatter.

---

README.md
autoload/codefmt/ocamlformat.vim
doc/codefmt.txt
instant/flags.vim
plugin/register.vim
vroom/ocamlformat.vroom

Add ocamlformat formatter

---

autoload/codefmt/jsbeautify.vim

Deduplicates per-filetype logic in AppliesToBuffer & FormatRange to use a shared `_supported_formats` definition. In the process, updates AppliesToBuffer to accept sass/scss/less filetypes, where #114 had only fixed them to work via explicit `:FormatCode jsbeautify` but not via `:FormatCode`.
@abgeana @awused FYI

Consolidate jsbeautify supported formats and allow for sass/scss/less

---

plugin/commands.vim

This is useful for allowing simple conditional formatting of buffers, e.g.,
```vim
autocmd FileType * if condition | AutoFormatBuffer | endif
```

Allow commands to be followed by a `|`.

---

autoload/codefmt/ktfmt.vim

(Fixes issue #218) When trying to use this locally, I was getting repeated errors that ktfmt was not available. Reversing the conditional here makes everything work correctly for me (on Linux), and also makes sense (success of a command line tool is indicated by return code equal to 0).

Fix broken ktfmt availability check

---

autoload/codefmt/dartfmt.vim
doc/codefmt.txt
instant/flags.vim
vroom/dartfmt.vroom

This is because `dartfmt` has been replaced by `dart format`.

Change the dartfmt_executable to point to "dart format".

---

autoload/codefmt/dartfmt.vim
doc/codefmt.txt
instant/flags.vim

d927656 changed the `dartfmt_executable` flag from a string to a list, but didn't change the use inside IsAvailable(), leading to:
```
Failed to evaluate whether formatter dartfmt is available: Vim(return):E730: Using a List as a String
```
The change uses the `ResolveFlagToArray()` helper in both `IsAvailable()` and `FormatRange()` (which incidentally also allows defining the flag using a Function), and updates the documentation for all flags using `ResolveFlagToArray()` to use the same phrasing.
Fixes #190.

Fix dartfmt's IsAvailable() method.

---

autoload/codefmt/juliaformatter.vim
bin/julia/.JuliaFormatter.toml
bin/julia/Manifest.toml
bin/julia/Project.toml
bin/julia/format.jl
bin/julia/install
bin/julia/install.cmd
doc/codefmt.txt
instant/flags.vim
plugin/register.vim
vroom/juliaformatter.vroom

This formatter uses a script wrapping the [JuliaFormatter.jl library](https://github.com/domluna/JuliaFormatter.jl).  This "formatter script in the plugin" approach hasn't been taken before in `vim-codefmt`, so let me know if you'd prefer a different approach or to reorganize things.  (The JuliaFormatter.jl library ships with an executable script, but it only works on file paths (not stdin) and can't handle line ranges.  I'm also not sure how to get the path of a bin directory in your Julia environment, which doesn't work like executables in a package management system like npm.)
If the user hasn't installed the `JuliaFormatter` package, instructions will point to an `install` script in the same directory as the formatter script.  I've tested the shell version of this script, but don't …

Add Julia formatter

---

README.md

Also sort lists, document which filetypes support Prettier, and match the AutoFormatBuffer example to the language list.  Formatting changed due to `mdformat` autoformatting.

Update README.md with missing languages

---

README.md
autoload/codefmt/ruff.vim
doc/codefmt.txt
instant/flags.vim
plugin/register.vim
vroom/ruff.vroom

Add ruff as formatter for Python

---

autoload/codefmt/ruff.vim
vroom/ruff.vroom

Forgot to pass the "-" placeholder for stdin. Apparently if you pass --stdin-filename ruff assumes stdin, but if there's no filename it can get confused and format everything in-place instead of formatting the editor buffer.
Fixes #223 (properly).

ruff formatter: Fix bug running non-stdin version
